package org.wattdepot.resource.source.summary;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotSame;
import javax.xml.datatype.XMLGregorianCalendar;
import org.wattdepot.util.tstamp.Tstamp;
import org.junit.Test;
import org.wattdepot.resource.source.summary.jaxb.SourceSummary;

/**
 * Ensures that the equals() and hashCode() methods that have been manually added to the JAXB
 * autogenerated code are working. This is important, because if the schema files are changed and
 * new Java code is generated via XJC, then the manually added methods will be silently blown away.
 * These tests act as a backstop to ensure that if that happens, tests will fail.
 * 
 * If we eventually move to autogenerated equals() and hashCode() via XJC plugins, then these tests
 * will confirm that the plugins are working properly.
 * 
 * @author Robert Brewer
 */
public class TestSourceSummaryJaxb {

  /**
   * Tests equals and hashCode for the SourceSummary type.
   * 
   * @throws Exception If there are problems creating a timestamp.
   */
  @Test
  public void testSourceSummary() throws Exception {
    String sourceUri = "http://localhost:8183/wattdepot/sources/foo";
    XMLGregorianCalendar firstTimestamp = Tstamp.makeTimestamp("2009-07-28T09:00:00.000-10:00");
    XMLGregorianCalendar lastTimestamp = Tstamp.makeTimestamp("2009-08-28T09:00:00.000-10:00");
    long dataCount = 2880L;
    SourceSummary summary1 = new SourceSummary();
    summary1.setHref(sourceUri);
    summary1.setFirstSensorData(firstTimestamp);
    summary1.setLastSensorData(lastTimestamp);
    summary1.setTotalSensorDatas(dataCount);
    SourceSummary summary2 = new SourceSummary();
    summary2.setHref(sourceUri);
    summary2.setFirstSensorData(firstTimestamp);
    summary2.setLastSensorData(lastTimestamp);
    summary2.setTotalSensorDatas(dataCount);

    assertNotSame("Two newly created SourceSummaries are the same object", summary1, summary2);
    assertEquals("Two SourceSummary objects with identical fields are not equal", summary1,
        summary2);
    assertEquals("Two SourceSummary objects with identical fields have different hashCodes",
        summary1.hashCode(), summary2.hashCode());
    summary2.setFirstSensorData(lastTimestamp);
    assertFalse("Different SourceSummaries are equal.", summary1.equals(summary2));
  }

  /**
   * Tests equals and hashCode for the SourceSummary type.
   * 
   * @throws Exception If there are problems creating a timestamp.
   */
  @Test
  public void testSourceSummaryToString() throws Exception {
    String expectedOutput =
        "SourceSummary [href=http://localhost:8183/wattdepot/sources/foo,"
            + " firstSensorData=2009-07-28T09:00:00.000-10:00,"
            + " lastSensorData=2009-08-28T09:00:00.000-10:00," + " totalSensorDatas=2880]";
    String sourceUri = "http://localhost:8183/wattdepot/sources/foo";
    XMLGregorianCalendar firstTimestamp = Tstamp.makeTimestamp("2009-07-28T09:00:00.000-10:00");
    XMLGregorianCalendar lastTimestamp = Tstamp.makeTimestamp("2009-08-28T09:00:00.000-10:00");
    long dataCount = 2880L;
    SourceSummary summary1 = new SourceSummary();
    summary1.setHref(sourceUri);
    summary1.setFirstSensorData(firstTimestamp);
    summary1.setLastSensorData(lastTimestamp);
    summary1.setTotalSensorDatas(dataCount);
    assertEquals("SourceSummary did not create expected toString", expectedOutput, summary1
        .toString());
  }
}
