//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.17 at 04:03:28 PM HST 
//


package org.wattdepot.resource.source.summary.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.wattdepot.resource.source.summary.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FirstSensorData_QNAME = new QName("", "FirstSensorData");
    private final static QName _Href_QNAME = new QName("", "Href");
    private final static QName _TotalSensorDatas_QNAME = new QName("", "TotalSensorDatas");
    private final static QName _LastSensorData_QNAME = new QName("", "LastSensorData");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.wattdepot.resource.source.summary.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SourceSummaries }
     * 
     */
    public SourceSummaries createSourceSummaries() {
        return new SourceSummaries();
    }

    /**
     * Create an instance of {@link SourceSummary }
     * 
     */
    public SourceSummary createSourceSummary() {
        return new SourceSummary();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FirstSensorData")
    public JAXBElement<XMLGregorianCalendar> createFirstSensorData(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_FirstSensorData_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Href")
    public JAXBElement<String> createHref(String value) {
        return new JAXBElement<String>(_Href_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TotalSensorDatas")
    public JAXBElement<Long> createTotalSensorDatas(Long value) {
        return new JAXBElement<Long>(_TotalSensorDatas_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LastSensorData")
    public JAXBElement<XMLGregorianCalendar> createLastSensorData(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_LastSensorData_QNAME, XMLGregorianCalendar.class, null, value);
    }

}
