package org.wattdepot.client;

import org.restlet.data.Status;

/**
 * An exception that is thrown when the WattDepot server encounters an error when performing an
 * operation.
 * 
 * @author Philip Johnson
 * @author Robert Brewer
 */
public class WattDepotClientException extends Exception {

  /** The default serial version UID. */
  private static final long serialVersionUID = 1L;

  /**
   * Contains the status for the request, if one was generated by the exception.
   */
  private transient Status status = null;
  
  /**
   * Thrown when an unsuccessful status code is returned from the Server.
   * 
   * @param status The Status instance indicating the problem.
   */
  public WattDepotClientException(Status status) {
    super(status.getCode() + ": " + status.getDescription());
    this.status = status;
  }

  /**
   * Thrown when an unsuccessful status code is returned from the Server.
   * 
   * @param status The status instance indicating the problem.
   * @param error The previous error.
   */
  public WattDepotClientException(Status status, Throwable error) {
    super(status.getCode() + ": " + status.getDescription(), error);
    this.status = status;
  }

  /**
   * Thrown when some problem occurs with Client not involving the server.
   * 
   * @param description The problem description.
   * @param error The previous error.
   */
  public WattDepotClientException(String description, Throwable error) {
    super(description, error);
  }

  /**
   * Thrown when some problem occurs with Client not involving the server.
   * 
   * @param description The problem description.
   */
  public WattDepotClientException(String description) {
    super(description);
  }

  /**
   * Returns the status received by the client, if any.
   * 
   * @return the status
   */
  public Status getStatus() {
    return status;
  }
}
